version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: pokemon_crawler
    volumes:
      - pg-data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pg-data:
